### ISSUE TITLE
Support for Xamarin.Forms with .NET Standard

### ISSUE THREAD

**Issue by mesheets** [jonathanpeppers/Xamarin.Forms.Mocks#14]
With [Xamarin.Forms 2.4 now supporting .NET Standard 2.0](https://developer.xamarin.com/guides/xamarin-forms/under-the-hood/net-standard/), might a [.NET Standard 2.0](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/) NuGet package target also be planned for inclusion with Xamarin.Forms.Mocks?

The current latest NuGet package appears to only support the earlier PCL profile targets, with a specific target of the following:
* portable-net45+win8+wpa81+wp8

Thank you!

**Comment by jonathanpeppers** [comment]
Hi @mesheets,

Do you know what I actually need to change? Is it simply a matter of adding a new directory in the NuGet package?

Right now it's doing this: https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/master/build.cake#L59

Is there a type of Xamarin.Forms project w/ .NET standard where Xamarin.Forms.Mocks isn't working?

**Comment by mesheets** [comment]
Hello @jonathanpeppers,

Based on the .NET Standard [documentation](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), .NET Standard is [described](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#comparison-to-portable-class-libraries) as the "replacement" for Portable Class Libraries (PCLs).  With .NET Standard, it isn't really that Xamarin.Forms.Mocks isn't working, but that rather than when switching apps or assemblies from PCL profiles to the new .NET Standard approach, .NET Standard prefers to reference other .NET Standard assemblies instead of PCL assemblies.

Is appears the Xamarin.Forms.Mocks PCL projects currently target [PCL Profile 259](https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/master/Xamarin.Forms.Mocks/Xamarin.Forms.Mocks.csproj#L13), so these projects would appear to be capable of targeting .NET Standard 1.0 without issue.

Regarding the NuGet package itself, NuGet packages can contain both PCL and .NET Standard "lib" folders.  (Xamarin.Forms 2.4 is actually an example of this, as its NuGet package contains both a "lib\netstandard1.0" folder as well as a "lib\portable-win+net45+wp80+wpa81" folder as cross-platform targets [in addition to the platform-specific targets that are also included in that NuGet package]).

To build assemblies for both the PCL assembly and the .NET Standard assembly, a project file would be needed for each.  Offhand, there are a few possible ways of approaching this, including the following:
* Copy the existing PCL project files as another file in the same directory but with a different name.
  * In the project file's XML, give the project a unique ProjectGuid (example of [line to modify](https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/master/Xamarin.Forms.Mocks/Xamarin.Forms.Mocks.csproj#L6)).
  * Save and then reload the project file in Visual Studio
  * Open the project properties page of this copied project file, and on the "Library" tab, click the link to "Target .NET Platform Standard" (in VS 2015)
    * If there are any existing NuGet package references, is it possible that they might need to be removed and then re-added after changing the target to ".NET Platform Standard"
    * As noted above, it appears these Xamarin.Forms.Mocks projects should be able to target .NET Standard 1.0
  * NOTE: Whenever a file is added to or removed from the project, both project files will need to be updated; the approach below might help mitigate this.
* Create a new .NET Standard project, but to avoid needing to maintain source files in multiple project files, also create a new "Shared" project
  * Move the source code to this Shared project
  * In the (new) .NET Standard project, add a reference to the newly-created Shared project
  * In the (existing) .NET PCL project, remove the the source files (as they are now part of the Shared project) and add a reference to the newly-created Shared project.
  * Both assemblies targeting both PCL and .NET Standard should now be able to be built, but management of the addition or removal of files would only need to be made in the Shared project

For the Xamarin.Forms.Mocks.Tests unit test project, if ever updating it to reference the .NET Standard project instead of the .NET PCL project, its "Target Framework Version" of [4.5](https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/master/Xamarin.Forms.Mocks.Tests/Xamarin.Forms.Mocks.Tests.csproj) should be fine as long as the .NET Standard project targets [1.0 or 1.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support); but if targeting later versions of .NET Standard, the version of the .NET Framework that the unit test project targets would need to be updated based on that [chart](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support).

**Comment by jonathanpeppers** [comment]
Thanks for the detailed response,

What is an example of something that would be broken if I didn't change anything? Something like a .NET Core (or standard) unit test project?

The question becomes, why would you use that? Is there a reason to not use a .NET 4.5/4.6 (full framework) unit test project? If you are targeting Xamarin, it seems better to me to run your unit tests on Mono than .NET Core.

**Comment by jonathanpeppers** [comment]
I'm going to close for now, anyone feel free to reopen if there is a good reason to port everything to .NET Standard.

**Comment by mesheets** [comment]
Microsoft's documentation states: ".NET Standard is the replacement for Portable Class Libraries (PCL)." With PCL going away and being replaced, a reason to upgrade to .NET Standard would be to continue to be able to use Xamarin.Forms.Mocks moving forward, as more projects adopt .NET Standard and deprecate older PCL versions.
* https://docs.microsoft.com/en-us/dotnet/standard/net-standard#comparison-to-portable-class-libraries

Additionally, this upgrade recommendation can also be found within the latest version of Visual Studio itself:
* Open the "Project Properties" window for the PCL project
* On the "Library" tab along the left side, find the "Targeting" section in the lower half of the tab content pane
* The current PCL targets will be listed
* At the very bottom of this "Targeting" section is the following quote:

> .NETStandard is the recommended method for sharing code between applications targeting different platforms.

Hope this helps provide some clarification. :-)

**Comment by jonathanpeppers** [comment]
@mesheets  try Xamarin.Forms.Mocks 2.5.0.3 on NuGet.

Just some open-source advice for the future: _in the time it took to write your detailed replies, you should have just send a PR instead!_

Even if you had trouble getting something to work, I would have gladly helped you through it.
