### ISSUE TITLE
2.5.0 support

### ISSUE THREAD

**Issue by Ivan-L** [jonathanpeppers/Xamarin.Forms.Mocks#15]
Hi there,

Now that Xamarin.Forms 2.5.0 is out (as well as 2.5.0 SR 1), please would you possibly publish a new version of Xamarin.Forms.Mocks which supports 2.5.0?

Is the alternative to download the Xamarin.Forms.Mocks and Xamarin.Forms.Mocks.Xaml code and include it in the solution until the NuGet package is published?

Thanks!

**Comment by jonathanpeppers** [comment]
Hi @Ivan-L,

Do you get an error if you _try_ using 2.5.0?

You can use the source, but there may be an API change that requires a code change in Mocks.

**Comment by Ivan-L** [comment]
Yes, there were errors when I tried. After cloning your repository, upgrading to Xamarin.Forms 2.5.0 and trying to build it, it is `IPlatformServices.QuitApplication` which is not implemented and therefore the cause of the failure. I suppose they introduced this as part of MacOS support.

So for now, I am using the source with the extra method implemented which throws a `NotImplementedException` and everything works.

**Comment by jonathanpeppers** [comment]
Ok, I'll put out an update soon, but feel free to send a PR of what you have if you have time, thanks!

**Comment by Ivan-L** [comment]
Ok, I have opened #16 with the upgraded packages and implementation of `IPlatformServices.QuitApplication` which is up for discussion.

**Comment by dagostinelli** [comment]
👍

**Comment by jBijsterboschNL** [comment]
+1

Is there an ETA when this update will be available?

**Comment by jonathanpeppers** [comment]
@Ivan-L @dagostinelli @jBijsterboschNL 

I just pushed 2.5.0.1 to NuGet, let me know if you have any issues.

**Comment by jBijsterboschNL** [comment]
Hi @jonathanpeppers, after updating, my unit tests are working again. Thanks for the quick fix. @Ivan-L thanks for your work as well!
