### ISSUE TITLE
Unhandled exception when Xaml page references StaticResource declared in App.xaml

### ISSUE THREAD

**Issue by jonathan-jd4software** [jonathanpeppers/Xamarin.Forms.Mocks#21]
I have made use of StaticResource to declare page styles etc.  They are all defined in App.xaml.
I get an unhandled exception when running a unit test on a ViewModel that triggers navigation to the Page using the StaticResource

[ERROR] FATAL UNHANDLED EXCEPTION: Xamarin.Forms.Xaml.XamlParseException: Position 7:18. StaticResource not found for key stackLayoutStyle

**Comment by jonathanpeppers** [comment]
Does your test create your App class and set Application.Current? Maybe in [SetUp]?

**Comment by jonathan-jd4software** [comment]
Hi @jonathanpeppers,  no it doesn't.  I will make the necessary change and get back to you as soon as I can.  Thanks.

**Comment by jonathan-jd4software** [comment]
Thank you for your help @jonathanpeppers, that has fixed the exception issue.  Thanks :)
