### ISSUE TITLE
.Net Standard

### ISSUE THREAD

**Issue by JanNepras** [jonathanpeppers/Xamarin.Forms.Mocks#22]
Would it be possible to port this nuget to .Net Standard?

**Comment by jonathanpeppers** [comment]
Sure, is there something that isn’t working right because it is a PCL?

**Comment by JanNepras** [comment]
I added this package to project "Unit Test Project (.NET Core)" and the Xamarin.Forms.Mock were unable to load.

**Comment by jonathanpeppers** [comment]
Ok another question then,

Why is your unit test project .Net Core? If you have an iOS and Android app, would it be better for your tests to run on Mono (full framework)?

**Comment by JanNepras** [comment]
This is the template in VS2017. Could you recommend me project template that works for VS2017?

**Comment by jonathanpeppers** [comment]
`Class Library (.NET Framework)` and add the NuGet for NUnit, XUnit or whichever.

**Comment by jonathanpeppers** [comment]
@JanNepras try Xamarin.Forms.Mocks 2.5.0.3 on NuGet.
