### ISSUE TITLE
Support for UriImageSource

### ISSUE THREAD

**Issue by acotterell1973** [jonathanpeppers/Xamarin.Forms.Mocks#26]
I really love this library.. but I'm facing an issue where I cannot seem to use the ImageSource in the unit test. I get the following

    var image = new Image { Source = new Uri("http://xamarin.com/img.png") };

The type initializer for `Xamarin.Forms.UriImageSource` threw an exception.

Is this something you can add the support for?

**Comment by jonathanpeppers** [comment]
Hi @acotterell1973 ,

Is this the same issue as #24? I put an update on NuGet that should resolve it, does version 2.5.0.4 fix your issue?

**Comment by acotterell1973** [comment]
Great. It’s the same issue. I had a problem upgrading. But the issue I believe is on my end. Once I figure it out. I will upgrade and try again. Thanks for the quick response.

**Comment by jonathanpeppers** [comment]
Ok feel free to reopen if you find an issue!
