### ISSUE TITLE
Add ability to update Forms Initialization

### ISSUE THREAD

**Issue by dansiegel** [jonathanpeppers/Xamarin.Forms.Mocks#29]
# Description

Many generic tests may be fine with a Runtime Platform of "Test" and "Unsupported" Idiom. However, there may be times where a developer is running complex tests that require changing either the Idiom or Runtime Platform. The Device class currently has a hidden method for updating the Idiom, but since the RuntimePlatform comes from the IPlatformServices instance (which is an internal class for XF.Mocks), we need to expose a way to allow developers to update the RuntimePlatform. It's worth noting that calling `MockForms.Init()` cannot be used to achieve this as `MockForms.Init()` registers services with the DependencyService which will result in an attempt to Add duplicate key to the DependencyImplementations. 

## Proposal

Update the API to something like:

```cs
internal class PlatformServices : IPlatformServices
{
    internal static PlatformServices Current { get; private set; }

    public string RuntimePlatform { get; set; }

    internal PlatformServices(string runtimePlatform)
    {
        RuntimePlatform = runtimePlatform;
        Current = this;
    }
}

public static class MockForms
{
    public static void UpdateRuntimePlatform(string runtimePlatform) =>
        PlatformServices.Current.RuntimePlatform = runtimePlatform;
}
```

A secondary consideration would be to use a bit of reflection to grab the DependencyImplementations as an IDictionary and call clear to ensure that we never add duplicate services.

**Comment by jonathanpeppers** [comment]
@dansiegel trying to refresh myself with this codebase (been a while), are you saying multiple calls to `MockForms.Init` doesn't work?

There are some tests in this repo doing this: https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/7cbc47bbb53078526389022b7cb3506b2cd90a46/Xamarin.Forms.Mocks.Tests/DeviceTests.cs#L28-L35

https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/7cbc47bbb53078526389022b7cb3506b2cd90a46/Xamarin.Forms.Mocks.Tests/DeviceTests.cs#L37-L44

Or is the "idiom" part what is broken?

**Comment by dansiegel** [comment]
I've run into an issue where calling MockForms.Init() multiple times results in an exception with the DependencyService throwing an exception due to the services that get re-registered:

```cs
Device.Idiom = idiom
DependencyService.Register<SystemResourcesProvider>();
DependencyService.Register<Serializer>();
DependencyService.Register<ValueConverterProvider>();
```

The way you're setting the Idiom btw is only possible because you have visibility into internals. Any consumers would have to call `SetIdiom`.

**Comment by jonathanpeppers** [comment]
I am confused... @dansiegel can you send a test that shows it broken?

I tried #30, but it worked for me on Windows locally.
