### ISSUE TITLE
Compatibility with Xamarin Forms 3.5?

### ISSUE THREAD

**Issue by uwiedemann** [jonathanpeppers/Xamarin.Forms.Mocks#34]
Since the update to [Xamarin Forms 3.5](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/3.5/3.5.0) there seems to be an issue with XF.Mocks (sorry for the German error message):

> System.TypeLoadException : Die Methode "GetNativeSize" im Typ "Xamarin.Forms.Mocks.PlatformServices" der Assembly "Xamarin.Forms.Core.UnitTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.
>    bei Xamarin.Forms.Mocks.MockForms.Init(String runtimePlatform, TargetIdiom idiom)

What in my interpretation means, that XF.Mocks does not find the implementation of GetNativeSize(), which was indeed [moved in XF 3.5](https://github.com/xamarin/Xamarin.Forms/pull/4235).

**Comment by jonathanpeppers** [comment]
Looks like we addressed this in #33, but for Xamarin.Forms 4.0.

Sounds like I should:
- Target XF 3.5 instead, post a updated NuGet package
- Unlist the old one that depends on XF 4.0

**Comment by memouwi** [comment]
Well, that would be great. 👍

**Comment by jonathanpeppers** [comment]
Should be live soon: https://www.nuget.org/packages/Xamarin.Forms.Mocks/3.5.0

I unlisted the 4.0.0.0-pre version, as I think it won't be needed.

**Comment by uwiedemann** [comment]
Thank you very much!
