### ISSUE TITLE
Version 3.5.0.169047 Support

### ISSUE THREAD

**Issue by koenigm-seattleu** [jonathanpeppers/Xamarin.Forms.Mocks#37]
Xamarin Forms version 3.5.0.169047 has the following error.  Downgrading forms to 3.5.0129 resolves the problem.

Message: System.TypeLoadException : 
Method 'OpenFileAsync' in type 'Xamarin.Forms.Mocks.IsolatedStorageFile' from assembly 'Xamarin.Forms.Core.UnitTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by jonathanpeppers** [comment]
@koenigm-seattleu I'm not able to reproduce this problem, it's working for me...

I'm not seeing changes to this interface that would cause this: https://github.com/xamarin/Xamarin.Forms/blob/6f5784a625fd2c2edfaa5ed5d4729f945b536238/Xamarin.Forms.Core/IIsolatedStorageFile.cs#L9-L19

Could you have had a mixture of Xamarin.Forms versions?

**Comment by koenigm-seattleu** [comment]
No mixture of forms, I made sure all match.  I can send you a project as an example.  contact me offline.

**Comment by jonathanpeppers** [comment]
You can email me at the address on my profile: https://github.com/jonathanpeppers

Was this on Windows? I tried to repro on Mac, and that is where I saw it working.

**Comment by jonathanpeppers** [comment]
@koenigm-seattleu can your students try: https://www.nuget.org/packages/Xamarin.Forms.Mocks/3.5.0.1

I think the issue you saw here was probably #38 (they posted an example, and I could see the problem myself).

**Comment by koenigm-seattleu** [comment]
Hope all is well.  Did you work out the issue?

On Jun 4, 2019, at 10:29 AM, Jonathan Peppers <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #37<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonathanpeppers%2FXamarin.Forms.Mocks%2Fissues%2F37&data=02%7C01%7Ckoenigm%40seattleu.edu%7C72b9e79b721d416026cd08d6e912228e%7Cbc10e052b01c48499967ee7ec74fc9d8%7C0%7C0%7C636952661445157924&sdata=D84yZUlU8scgEO8ZI6b4MZvf5VYm3QiTAhbK9sVwpFo%3D&reserved=0>.

**Comment by jonathanpeppers** [comment]
Yes, I think there were hitting #38

**Comment by koenigm-seattleu** [comment]
If I recall from the students, it happened to those who were using standard rather than shared projects for the shared code.



On Jun 4, 2019, at 11:46 AM, Jonathan Peppers <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I think there were hitting #38<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonathanpeppers%2FXamarin.Forms.Mocks%2Fissues%2F38&data=02%7C01%7Ckoenigm%40seattleu.edu%7C3cb04b8dae3241698f3608d6e91ce3be%7Cbc10e052b01c48499967ee7ec74fc9d8%7C0%7C0%7C636952707630661491&sdata=HqrE7Cylb1CkBWFVDIE45rY05CXMJcutq%2FYLJCpD62U%3D&reserved=0>
