### ISSUE TITLE
Mock the new OnPlatform mechanism

### ISSUE THREAD

**Issue by lanarchyste** [jonathanpeppers/Xamarin.Forms.Mocks#4]
The new mechanism uses a class provided by the IoC implementing the IValueConverterProvider interface.

When I use the OnPlatform from the unit tests, the IValueConverterProvider implementation provided by DependencyService is always null.

Is it possible to update the code so that the DependencyService returns the correct implementation? Or at least be able to add our own implementation?

Thank you very much.

Best regards.
Julien

**Comment by jonathanpeppers** [comment]
Hi Julien,

Do you have a quick unit testing showing this is broken? I would like to add it to my test suite.

If I'm following correctly, I think there may be two things I need to look into:
1. Make sure `DependencyService` is testable
1. Make sure `IValueConverterProvider` is implemented if Xamarin.Forms depends on it internally

I have a few tests with `Device.RuntimePlatform` implementation, but not `OnPlatform`: https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/master/Xamarin.Forms.Mocks.Tests/DeviceTests.cs#L27

**Comment by lanarchyste** [comment]
Here is an example of a unit test :

```
[Test]
public void GetOnPlatformValue()
{
    var platformColor = new OnPlatform<Color>();
    platformColor.Platforms.Add(new On
    {
        Value = Color.Red,
        Platform = new List<string> { Device.RuntimePlatform }
    });
    
    Assert.AreEqual("FF0000", ((Color)platformColor).ToHex());
}
```
The result returns Color.Black (which is the default color) instead of returning Color.Red

I had the expected behavior by adding a static class in Xamarin.Forms.Mock.Xaml and adding the following code:

```
namespace Xamarin.Forms.Xaml
{
    public static class MockXaml
    {
        public static void Init()
        {
            DependencyService.Register<ValueConverterProvider>();
        }
    }
}
```

I think doing just that is enough.
