### ISSUE TITLE
Finding external classes in MarkupExtensions Tests Failing

### ISSUE THREAD

**Issue by adamhill** [jonathanpeppers/Xamarin.Forms.Mocks#40]
I have a test for a MarkupExtension that is failing.

The code is:
```csharp 
var label = new Label();
label.LoadFromXaml("<Label xmlns:f=\"clr-namespace:PaycorEmployee.Helpers;assembly=PaycorEmployee\" Text=\"{f:StringResource}\" />");
label.Text.Should().Be("");
```

Pretty much the example code from GH.

The error is:
```
Xamarin.Forms.Xaml.XamlParseException : Position 1:79. MarkupExtension not found for f:StringResource
   at Xamarin.Forms.Xaml.ExpandMarkupsVisitor.MarkupExpansionParser.Parse(String match, String& remaining, IServiceProvider serviceProvider)
   at Xamarin.Forms.Xaml.ExpandMarkupsVisitor.ParseExpression(String& expression, IXmlNamespaceResolver nsResolver, IXmlLineInfo xmlLineInfo, INode node, INode parentNode)
   at Xamarin.Forms.Xaml.ExpandMarkupsVisitor.Visit(MarkupNode markupnode, INode parentNode)
```
My MarkupExtensions is not in the Test, but if I try and "Add Existing" with the class file to the UnitTest project, it does complain that there is already a class name that in the project. telling me the Reference to the main project is definitely getting picked up.

Are there some other hints I need to provide LoadFromXAML() in order to get the parse to see the external MarkupExtension? Or is this a bug?

Thanks.

**Comment by jonathanpeppers** [comment]
@adamhill you can try the update here, until there is an update on NuGet: https://ci.appveyor.com/project/jonathanpeppers/xamarin-forms-mocks/builds/24873567/artifacts
