### ISSUE TITLE
MockForms.Init() having issue with MasterBehavior.Popover;

### ISSUE THREAD

**Issue by koenigm-seattleu** [jonathanpeppers/Xamarin.Forms.Mocks#49]
I am adding coverage to the default example xamarin forms app to get as highest coverage as possible.  I noticed that the MainPage.xaml.cs has an issue even after having the UT call MockForms.Init().  I realize that the coverage of this file would not be high priority. 

The issue is due to the call to MasterBehavior.

MasterBehavior = MasterBehavior.Popover;

Steps: 
Run the New Project Template for Xamarin Forms UWP.

Add nUnit Unit Tests Project.

Create a UT for MainPage.xaml.cs  (MainPageTests.cs)
        [Test]
        public void MainPage_Constructor_Default_Should_Pass()
        {
            // Arrange

            // Initilize Xamarin Forms
            MockForms.Init();

            // Act
            var result = new MainPage();

            // Assert
            Assert.IsNotNull(result);
        }

-------------

using Mine.Models;
using System.Collections.Generic;
using System.ComponentModel;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace Mine.Views
{
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    /// <summary>
    /// Main Page
    /// </summary>
    [DesignTimeVisible(false)]
    public partial class MainPage : MasterDetailPage
    {
        // Collection of Navigation Pages
        Dictionary<int, NavigationPage> MenuPages = new Dictionary<int, NavigationPage>();

        /// <summary>
        /// Constructor setups the behavior and menu pages
        /// </summary>
        public MainPage()
        {
            InitializeComponent();

            MasterBehavior = MasterBehavior.Popover;
        }

        /// <summary>
        /// Process the Menu Selected item
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task NavigateFromMenu(int id)
        {
            // See if the Page is in memory, if not load it
            if (!MenuPages.ContainsKey(id))
            {
                switch (id)
                {
                    case (int)MenuItemEnum.Items:
                        MenuPages.Add(id, new NavigationPage(new ItemIndexPage()));
                        break;
                    case (int)MenuItemEnum.About:
                        MenuPages.Add(id, new NavigationPage(new AboutPage()));
                        break;
                }
            }

            // Switch to the Page
            var newPage = MenuPages[id];

            if (newPage != null && Detail != newPage)
            {
                Detail = newPage;

                // Android needs a deal, iOS and UWP does not
                if (Device.RuntimePlatform == Device.Android)
                {
                    await Task.Delay(100);
                }

                IsPresented = false;
            }
        }
    }
}

**Comment by jonathanpeppers** [comment]
@koenigm-seattleu it looks like I can reproduce the issue:
```
 System.InvalidOperationException : You MUST call Xamarin.Forms.Init(); prior to using it.
```

With just these 2 lines:
```csharp
MockForms.Init();
Xamarin.Forms.Device.Info.ToString();
```

It looks like Xamarin.Forms.Mocks needs to set `Device.Info` and it's never done that?

**Comment by jonathanpeppers** [comment]
Try the update and let me know, thanks. It should be live shortly:

https://www.nuget.org/packages/Xamarin.Forms.Mocks/3.5.0.3

**Comment by koenigm-seattleu** [comment]
I will try.  

Ran into a VS problem that is blocking me.  I can't get any output for code coverage in VS 19 enterprise with previous projects, or a new projects.  I did a full VS repair which did not fix the issue.

Test pass when run in test explorer, but CC gives 0 blocks covered with "Empty results generated: No binaries were instrumented. Make sure the tests ran, required binaries were loaded, had matching symbol files, and were not excluded through custom settings. For more information see https://go.microsoft.com/fwlink/?LinkID=253731"

test output window
[2/9/2020 6:37:36.127 PM] ---------- Run started ----------
NUnit Adapter 3.16.1.0: Test execution started
Running selected tests in C:\repros\4250WQ\Mine\Mine\UnitTests\bin\Debug\netcoreapp3.1\UnitTests.dll
   NUnit3TestExecutor converted 63 of 63 NUnit test cases
NUnit Adapter 3.16.1.0: Test execution complete
[2/9/2020 6:37:38.216 PM] ========== Run finished: 63 tests run (0:00:02.0344722) ==========

So I need to clear that issue.  Unfortunate, because I was able to get coverage numbers before thus the issue report...

**Comment by koenigm-seattleu** [comment]
Figured out the CC issue in VS.  Turns out the Microsoft.Net.Test.SDK version 16.3 and higher fail to generate CC results, downgrading to 16.2.0 works.

Thanks for the update to the package.  I will continue to add tests to the project, and will post issues if I come across them.
