### ISSUE TITLE
Unable to use with XF version 4.7

### ISSUE THREAD

**Issue by VladislavAntonyuk** [jonathanpeppers/Xamarin.Forms.Mocks#51]
Message: 
    System.TypeLoadException : Method 'GetHash' in type 'Xamarin.Forms.Mocks.PlatformServices' from assembly 'Xamarin.Forms.Core.UnitTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
  Stack Trace: 
    MockForms.Init(String runtimePlatform, TargetIdiom idiom)

**Comment by VladislavAntonyuk** [comment]
Yes, I am verified it on nightly build

**Comment by jonathanpeppers** [comment]
@VladislavAntonyuk if you want to ping me when there is a preview on nuget.org, I'll look into this.

I don't want to fix something on a nightly build, they may yet change it before there is a preview.

**Comment by VladislavAntonyuk** [comment]
Ok, I think 4.7 pre1 will be released in a month

**Comment by dansiegel** [comment]
the nightly's generally run a minor version ahead of what the actual release version is... 4.6 that was released an hour ago has some breaks

**Comment by VladislavAntonyuk** [comment]
@jonathanpeppers 4.6 is released, could you please take a look how it breaks XF.Mocks

**Comment by VladislavAntonyuk** [comment]
@jonathanpeppers The issue is still reproduced:
 Message: 
    System.TypeLoadException : Method 'GetHash' in type 'Xamarin.Forms.Mocks.PlatformServices' from assembly 'Xamarin.Forms.Core.UnitTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
  Stack Trace: 
    MockForms.Init(String runtimePlatform, TargetIdiom idiom, OSAppTheme requestedTheme)
