### ISSUE TITLE
Method 'GetNamedColor' does not have an implementation.

### ISSUE THREAD

**Issue by SeRgI1982** [jonathanpeppers/Xamarin.Forms.Mocks#56]
Hi,

I have noticed that my UnitTests  stopped working because of that:

System.TypeLoadException : Method 'GetNamedColor' in type 'Xamarin.Forms.Mocks.PlatformServices' from assembly 'Xamarin.Forms.Core.UnitTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Xamarin.Forms is in a version 4.6.0.726

![Screenshot 2020-05-08 at 10 14 55](https://user-images.githubusercontent.com/9572525/81386303-1754de00-9115-11ea-91c9-f051a30e064a.png)

**Comment by jonathanpeppers** [comment]
Are you using? https://www.nuget.org/packages/Xamarin.Forms.Mocks/4.6.0.1

This should have been fixed by: https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/pull/52

**Comment by SeRgI1982** [comment]
Sorry, my fault. 
I guess that I had problem with connection to NuGet server because there wasn't a notification icon about the latest version. Now, after updating to the latest version, everything works great :)

**Comment by jonathanpeppers** [comment]
I forgot to publish this release on Github, so hopefully will be easier to spot next time, thanks!

https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/releases/tag/4.6.0.1
