### ISSUE TITLE
4.8 version coming?

### ISSUE THREAD

**Issue by davidaramant** [jonathanpeppers/Xamarin.Forms.Mocks#60]
Is this library still being maintained? We're getting a lot of random exceptions using this in a project with Forms 4.8 that all seem to be threading race conditions.

**Comment by jonathanpeppers** [comment]
> Is this library still being maintained?

I think a better description would be that it is "done". Fixes are only needed when Xamarin.Forms changes. This library relies on a few private APIs, so it can break when newer Xamarin.Forms versions come out.

> We're getting a lot of random exceptions using this in a project with Forms 4.8 that all seem to be threading race conditions.

Can you post the stack trace? Better yet, can you reproduce the problem in the [unit test project](https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/tree/master/Xamarin.Forms.Mocks.Tests)?

**Comment by davidaramant** [comment]
One issue is that setting there seems to be a race condition for setting the idiom.  Any test with a call like `MockForms.Init("Test", TargetIdiom.Phone);` will sporadically fail because it's using the wrong idiom.  The code under test is calling `Device.Idiom == TargetIdiom.Phone` and sometimes that check is false.

Here is a stack trace from a recent crash.  Again, very sporadic failures.  If you told me this was ultimately a bug with the {{Shell}} control I would believe you because we're having a lot of problems with it.

> [xUnit.net 00:00:01.94]     ForumMobile.UnitTests.Common.Navigation.NavigationServiceTests.ShouldRaiseEventAndSwapShellsWhenLoggingOutFromMenu [FAIL]
>   X ForumMobile.UnitTests.Common.Navigation.NavigationServiceTests.ShouldRaiseEventAndSwapShellsWhenLoggingOutFromMenu [31ms]
>   Error Message:
>    System.ArgumentException : An item with the same key has already been added. Key: Xamarin.Forms.BindableProperty
>   Stack Trace:
>      at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
>    at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
>    at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
>    at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value)
>    at Xamarin.Forms.BaseShellItem.Propagate(BindableProperty property, BindableObject from, BindableObject to, Boolean onlyToImplicit)
>    at Xamarin.Forms.BaseShellItem.PropagateFromParent(BindableProperty property, Element me)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.VisualElement.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.BaseShellItem.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.ShellSection.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.ShellItem.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children)
>    at Xamarin.Forms.Shell.Xamarin.Forms.IPropertyPropagationController.PropagatePropertyChanged(String propertyName)
>    at Xamarin.Forms.Element.OnParentSet()
>    at Xamarin.Forms.NavigableElement.OnParentSet()
>    at Xamarin.Forms.Page.OnParentSet()
>    at Xamarin.Forms.Element.set_Parent(Element value)
>    at Xamarin.Forms.Application.set_MainPage(Page value)
>    at ForumMobile.Common.Navigation.NavigationService.SwitchShell(Shell shell) in /Users/forumbuilduser/builds/GUeQtQma/0/forum-cu/forum-mobile/src/ForumMobile/ForumMobile/Common/Navigation/NavigationService.cs:line 163
>    at ForumMobile.Common.Navigation.NavigationService.LogIn() in /Users/forumbuilduser/builds/GUeQtQma/0/forum-cu/forum-mobile/src/ForumMobile/ForumMobile/Common/Navigation/NavigationService.cs:line 36
>    at ForumMobile.UnitTests.Common.Navigation.NavigationServiceTests.ShouldRaiseEventAndSwapShellsWhenLoggingOutFromMenu() in /Users/forumbuilduser/builds/GUeQtQma/0/forum-cu/forum-mobile/src/ForumMobile/ForumMobile.UnitTests/Common/Navigation/NavigationServiceTests.cs:line 92

**Comment by jonathanpeppers** [comment]
> One issue is that setting there seems to be a race condition for setting the idiom.  Any test with a call like `MockForms.Init("Test", TargetIdiom.Phone);` will sporadically fail because it's using the wrong idiom.  The code under test is calling `Device.Idiom == TargetIdiom.Phone` and sometimes that check is false.

The value for `TargetIdiom` is just a static field:

https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/blob/35a55d2d314db760c7e4fed2e6b8671e010aaa44/Xamarin.Forms.Mocks/MockForms.cs#L20

You can't expect to set it to different values on different threads and assert against its value?

Same with the other error, it seems to be calling the static `Application.MainPage` on two different threads:

```
at Xamarin.Forms.Application.set_MainPage(Page value)
```

I would not recommend running these tests in parallel. Xamarin.Forms doesn't consider these things changing on multiple threads because it wouldn't happen in a real app. You can't have two `MainPage`'s at once or two different `Idiom` in a real app.

**Comment by davidaramant** [comment]
We're not explicitly launching any new threads in the tests so it must be XUnit's default behavior of running all the test classes in parallel.  The idiom stuff makes perfect sense - another test class must be setting a different `Idiom` at the same time.  Wrapping the idiom stuff in a mockable interface seems like an easy fix for that issue.

I think we can fix the other issues with XUnit test categories or through some other means.

Thanks for the help anyway!
