### ISSUE TITLE
Support for Xamarin.Essentials

### ISSUE THREAD

**Issue by CarloBauer** [jonathanpeppers/Xamarin.Forms.Mocks#66]
I have VersionTracking enabled on my App and want to initialize it as described in your README.md,after this i get an 'System.TypeInitializationException' in Xamarin.Essentials.dll. So it could be an Issue but mainly it is an Question:
Does this Library Works with Xamarin.Essentials? Thanks in advance.

**Comment by CarloBauer** [comment]
Nevermind Xamarin.Essentials doesnt support Unit-Testing directly.

**Comment by jonathanpeppers** [comment]
Yeah if I download: https://www.nuget.org/packages/Xamarin.Essentials/1.6.0

There is a netstandard assembly that does this everywhere:

```csharp
throw ExceptionUtils.NotSupportedOrImplementedException;
```

If you need to test Xamarin.Essentials, it would probably be easiest to put all interactions with XE in its own class so you can have a mock version for unit tests. There might also be a mocking library (like Moq) that works with XE, I'm not sure.
