### ISSUE TITLE
Add Xamarin.Forms 5 support

### ISSUE THREAD

**Issue by tomkecy** [jonathanpeppers/Xamarin.Forms.Mocks#68]
Hi,
I've updated my Xamarin project to Xamarin.Froms 5.0.0.2012 and it seems that Xamarin.Forms.Mocks doesn't support it. Would it be possible to add such support to Xamarin.Forms.Mocks?

Thanks!

**Comment by jonathanpeppers** [comment]
Can you share the error message you get? Exception message & stack trace?

**Comment by jonathanpeppers** [comment]
Closing for now, let me know if you can share more info.

I made the README a bit clearer showing that future versions of Xamarin.Forms will probably work (until they don't 😄):

![image](https://user-images.githubusercontent.com/840039/114248623-ba355e00-995d-11eb-9612-d40ef99c1350.png)
