### ISSUE TITLE
Xamarin Forms 2.3.5 support?

### ISSUE THREAD

**Issue by michelmoorlag** [jonathanpeppers/Xamarin.Forms.Mocks#7]
I have a Xamarin Forms 2.3.4.247 solution with a unit tests project using Moq (https://www.nuget.org/packages/Moq/) version 4.7.99. and Xamarin.Forms.Mocks 2.3.4.3. All unit tests run fine.

After upgrading Xamarin Forms to version 2.3.5.256-pre6 I have rebuild my solution. Now when I try to run the unit tests in the ClassInitialize method on line "Xamarin.Forms.Mocks.MockForms.Init();" I get the exception:
Could not load type 'Xamarin.Forms.IPlatformServices' from assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by jonathanpeppers** [comment]
Hmm, I think this means they moved a namespace in 2.3.5:

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/IPlatformServices.cs#L9

I'll have to make a new release targeting 2.3.5. This is one of the dilemmas of this library: having to rely on internal Xamarin.Forms APIs.

I'll be able to look at this soon, but if you want to take a stab yourself, feel free. I'll help you through any PRs you send. I would start by updating the Xamarin.Forms NuGet to 2.3.5.

**Comment by michelmoorlag** [comment]
Hi Jonathan, thank you for your answer.
If you could take a look before XF 2.3.5 is stable that would be really nice.
I am a bit uncertain how and if I could fix this.

**Comment by michelmoorlag** [comment]
Hi Jonathan, thank you for your answer.
If you could take a look before XF 2.3.5 is stable that would be really nice.
I am a bit uncertain how and if I could fix this.

**Comment by michelmoorlag** [comment]
I pushed the wrong button :(
Reopened the issue

**Comment by jonathanpeppers** [comment]
@michelmoorlag I put up a prerelease version supporting 2.3.5: https://www.nuget.org/packages/Xamarin.Forms.Mocks/2.3.5.1-pre6

Does it work for you?

**Comment by michelmoorlag** [comment]
It certainly does, unit tests run like a charm with 2.3.5-pre6.
Thank you very much!

**Comment by jonathanpeppers** [comment]
Ok, I'll put up a final stable package when Xamarin.Forms puts one up.

**Comment by michelmoorlag** [comment]
Perfect!
