### ISSUE TITLE
Asserting Height and Width Properties of VisualElements inside of Layouts returns -1

### ISSUE THREAD

**Issue by mikekirby** [jonathanpeppers/Xamarin.Forms.Mocks#70]
I want to write unit tests that can assert on UI properties that are calculated when they are added to pages with various layouts. Is this possible with XF.Mocks? I found example unit tests in XF that assert on these properties, but the layout needed "IsPlatformEnabled = true" and a call to Layout(new Rectangle(0,0,200,200)) to set an artificial screen size.

see: [StackLayoutUnitTests](https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Core.UnitTests/StackLayoutUnitTests.cs#L70)

```C#
using NUnit.Framework;

namespace Xamarin.Forms.Mocks.Tests
{
    [TestFixture]
    public class LayoutTests
    {
        [SetUp]
        public void SetUp()
        {
            MockForms.Init();
            Application.Current = new App();
        }

        [TearDown]
        public void TearDown()
        {
            Application.Current = null;
        }

        [Test]
        public void ShouldSetHeightOfChildren()
        {
            var child = new Label { Text = "Derek", HeightRequest = 20 };

            Application.Current.MainPage = new ContentPage
            {
                Content = new StackLayout
                {
                    Orientation = StackOrientation.Vertical,
                    Children = { child }
                }
            };

            Assert.AreEqual(expected: 20, child.Height);
        }
    }
}
```

**Comment by jonathanpeppers** [comment]
I think you probably need to call `Measure (double.MaxValue, double.MaxValue)` on one of the views.

Such as:

https://github.com/jonathanpeppers/Xamarin.Forms.Benchmarks/blob/0943ba0a9c3fca9468184671afc9ca96c051696f/Xamarin.Forms.Benchmarks/Benchmarks/Layouts.cs#L33-L53

I'll try to get a better example later, but let me know if you get it to work.

**Comment by mikekirby** [comment]
Thanks for the quick response. I think there is a misunderstanding. I was expecting something to trigger an event to set the height and width of all the visual elements in a layout, as if it were rendered.

**Comment by mikekirby** [comment]
Here is what I have that appears update the visual elements, but I don't think it is suitable for production code, see "IsPlatformEnabled=true"

```C#
using NUnit.Framework;

namespace Xamarin.Forms.Mocks.Tests
{
    [TestFixture]
    public class LayoutTests
    {
        public Rectangle PageBounds =>
            new Rectangle(
                x: 0,
                y: 0,
                width: Device.Info.PixelScreenSize.Width,
                height: Device.Info.PixelScreenSize.Height);

        [SetUp]
        public void SetUp()
        {
            MockForms.Init();
            Application.Current = new App();
        }

        [TearDown]
        public void TearDown()
        {
            Application.Current = null;
        }

        [Test]
        public void ShouldUpdateLabelHeight()
        {
            var child = new Label
            {
                IsPlatformEnabled = true,
                Text = "Mount Elbert",
                HeightRequest = 6
            };

            Application.Current.MainPage = new ContentPage
            {
                IsPlatformEnabled = true,
                Content = new StackLayout
                {
                    IsPlatformEnabled = true,
                    HeightRequest = 5,
                    Orientation = StackOrientation.Vertical,
                    Children = { child }
                }
            };

            Application.Current.MainPage.Layout(PageBounds);
            Application.Current.MainPage.ForceLayout();

            Assert.AreEqual(expected: 6, child.Height);
        }
    }
}

```

**Comment by jonathanpeppers** [comment]
I think your test can be simplified to something like:
```csharp
[TestFixture]
public class LayoutTests
{
    public Rectangle MaxRectangle =>
        new Rectangle(
            x: 0,
            y: 0,
            width: double.MaxValue,
            height: double.MaxValue);

    [SetUp]
    public void SetUp()
    {
        MockForms.Init();
    }

    [Test]
    public void ShouldSetWidthsOfChildren()
    {
        var child = new Label
        {
            IsPlatformEnabled = true,
            Text = "Derek",
            HeightRequest = 20
        };
        var layout = new StackLayout
        {
            Orientation = StackOrientation.Vertical,
            Children = { child }
        };

        layout.Layout(MaxRectangle);

        Assert.AreEqual(expected: 20, child.Height);
    }
}
```

I think `IsPlatformEnabled` is the trick, and you can set it on the `View` you are asserting against?

**Comment by mikekirby** [comment]
Thank you for the simplifications, I updated the example to keep things simple and remove unnecessary code.
 
In testing a ContentPage it appears to require the Content and all the logical children to have the IsPlatformEnabled set "true".

I wrote a hack that does this, but ideally we'd have a Mock platform so that the view classes can do their own IsPlatformEnabled=true on the RendererProperty change notification. But I haven't looked into wiring this yet. Thoughts? Also keep in mind I am trying to unit test production code that will not have "IsPlatformEnabled = true" hard coded.

```C#
using NUnit.Framework;
using Xamarin.Forms.Internals;

namespace Xamarin.Forms.Mocks.Tests
{
    [TestFixture]
    public class LayoutTests
    {
        [SetUp]
        public void SetUp()
        {
            MockForms.Init();
        }

        [Test]
        public void ShouldUpdateLabelHeight()
        {
            var child = new Label
            {
                Text = "Mount Elbert",
                HeightRequest = 6
            };

            var page = new ContentPage
            {
                Content = new StackLayout
                {
                    Orientation = StackOrientation.Vertical,
                    Children = { child }
                }
            };

            LayoutPage(page, height: 1920, width: 1080);
            Assert.AreEqual(expected: 6, child.Height);
        }

        protected void LayoutPage(ContentPage page, double height=double.MaxValue, double width=double.MaxValue)
        {
            page.Content.IsPlatformEnabled = true;
            page.Content.LogicalChildren
                .ForEach(c => (c as VisualElement).IsPlatformEnabled = true);

            page.Layout(new Rectangle(x: 0,y: 0, width: width, height: height));
        }
    }
}
```

**Comment by jonathanpeppers** [comment]
@mikekirby unfortunately, I don't see a global place that Xamarin.Forms.Mocks could set `IsPlatformEnabled` automatically...

It seems like they set it in each renderer:

* https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs#L46
* https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.Android/VisualElementPackager.cs#L124

It would have been nice if I could do something in `MockForms.Init()`, but I don't see how.

**Comment by mikekirby** [comment]
I agree, but I am happy to have found how to clear some initial hurdles and learn something more about Xamarin.Forms in the process. Thanks @jonathanpeppers!
