### ISSUE TITLE
Navigation with AppShell for Xamarin Forms 5

### ISSUE THREAD

**Issue by Axel3232** [jonathanpeppers/Xamarin.Forms.Mocks#71]
Hi 

Looks like the navigation is broken with the new AppShell for Xamarin Forms 5.
When navigating from a viewModel using : `await Shell.Current.GoToAsync("///main");`

the `MainPage.Navigation.NavigationStack` has only one item but with null value.

Thank you anyway for your great work !

**Comment by jonathanpeppers** [comment]
I've not tried testing shell navigation. Could you share an example test?

Or better yet, if you sent a pull request that adds a test to this project here: 

https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/tree/master/Xamarin.Forms.Mocks.Tests

Thanks!

**Comment by Axel3232** [comment]
Ok after some test I realized that the problem was on  my side, so you can close the issue ;)
